server:
  port: 8123
  servlet:
    context-path: /api
spring:
  profiles:
    # 默认开发模式，拉下代码直接跑
    active: prod
  application:
    name: sei-pic-backend
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${my.db.url}
    username: ${my.db.username}
    password: ${my.db.password}
  # Redis 配置
  redis:
    database: 0
    host: ${my.redis.host}
    port: 6379
    timeout: 5000ms
    password: ${my.redis.password}

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: '' # 关闭日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# swagger
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.sei.seipicbackend.controller
  basic:
    password: ${my.knife4j.basic.password} #swagger的账号密码
    username: ${my.knife4j.basic.username}
# 腾讯云cos对象存储
cos:
  client:
    host: ${my.cos.host}
    secretId: ${my.cos.secretId}
    secretKey: ${my.cos.secretKey}
    region: ${my.cos.region}
    bucket: ${my.cos.bucket}
# 阿里云百炼
aliYunAi:
  apiKey: ${my.ali.apiKey}
# 其他配置
user:
  salt: ${my.user.salt}
  defaultPwd: ${my.user.defaultPwd}
