server:
  port: 8123
  servlet:
    context-path: /api
spring:
  servlet:
    # 上传文件大小限制
    multipart:
      max-file-size: 10MB
  profiles:
    # 使用local配置
    active: local
  application:
    name: sei-pic-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${my.db.url}
    username: ${my.db.username}
    password: ${my.db.password}
  # Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000ms

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# swagger
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.sei.seipicbackend.controller
# 腾讯云cos对象存储
cos:
  client:
    host: ${my.cos.host}
    secretId: ${my.cos.secretId}
    secretKey: ${my.cos.secretKey}
    region: ${my.cos.region}
    bucket: ${my.cos.bucket}
# 阿里云百炼
aliYunAi:
  apiKey: ${my.ali.apiKey}
# 其他配置
user:
  salt: ${my.user.salt}
  defaultPwd: ${my.user.defaultPwd}
